services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-16-alpine}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: "${POSTGRES_DB:-tournament-app}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: "postgres:${POSTGRES_VERSION:-16-alpine}"
    tmpfs:
        - /pgtmpfs
    ports:
      - "${POSTGRES_TEST_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /pgtmpfs

volumes:
  postgres-data:
